<?php

use Drupal\views\ViewExecutable;
/**
 * @file
 * bootstrap5 Sub Theme "covid_custom_theme" theme file.
 */

 /**
  * Implements hook_theme_suggestions_page_alter().
  */
function covid_custom_theme_theme_suggestions_page_alter(array &$suggestions, array $variables) {
  if ($node = \Drupal::routeMatch()->getParameter('node')) {
    $suggestions[] = 'page__' . $node->bundle();
  }
}

/**
 * Implements hook_preprocess_node().
 */
function covid_custom_theme_preprocess_node(&$variables){
  $variables['is_front'] = \Drupal::service('path.matcher')->isFrontPage();
  $node = $variables['node'];
  $hide_page_title = [
    'Events',
    'News',
    'Resources',
  ];
  if (!empty($node)) {
    $title = $node->title->value;
  }
  if (!empty($title) && in_array($title, $hide_page_title)) {
    $variables['hide_page_title'] = TRUE;
  }
}
