_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: db582508-889d-4977-8565-6aca6b9680a4
name: 'Covid Vaccination Center'
mail: akashkumargupta1993@gmail.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node/4
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
