<?php

use Drupal\views\ViewExecutable;
use Drupal\user\Entity\User;
use Drupal\node\Entity\Node;


function covid_custom_module_views_pre_view(ViewExecutable $view, $display_id, array &$args) {
  // Modify contextual filters for other cities view based on country term page
  $account = \Drupal::currentUser();
  if ($view->id() == 'other_cities' && $display_id == 'block_other_cities') {
    $user = User::load($account->id());
    $country = $user->get('field_country')->getValue();
    if(!empty($country)) {
      $args[0] = $country[0]['target_id'];
    }
  }

  // Modify contextual filters to pass user city for view
  if ($view->id() == 'covid_centers' && $display_id == 'block_city_covid_centres') {
    $user = User::load($account->id());
    $city = $user->get('field_city')->getValue();
    if(!empty($city)) {
      $args[0] = $city[0]['target_id'];
    }
  }

  // Modify contextual filters to pass node city based on current covid centre
  if ($view->id() == 'other_covid_centers' && $display_id == 'block_other_covid_centre') {
    $node = \Drupal::routeMatch()->getParameter('node');
    if ($node instanceof \Drupal\node\NodeInterface) {
      $nid = $node->id();
      $city = $node->get('field_city')->getValue();
      if(!empty($city))
        $args[0] = $city[0]['target_id'];
    }
  }
}

/**
 * Implements hook_theme().
 */
function covid_custom_module_theme($existing, $type, $theme, $path) {
  return [
    'covid_register' => [
      'variables' => [
        'register_link' => NULL,
        'covid_nid'=> NULL,
        'register_text' => NULL,
      ],
    ],
  ];
}
